### ISSUE TITLE
Some apps not entering VR mode

### ISSUE THREAD

**Issue by skygate2012** [DavidModPhone/DaydreamVR_Service#1]
Hey, first of all thank you so much for bringing the newest module. I was finally able to pair the controller and not bootloop with this one. One issue is that it seems most games (like _Blade Runner_, _Ultrawings_, _Untethered_, etc. I downloaded them from [this repo](https://github.com/Nargajuna/DaydreamExperiencesArchive)) don't recognize the VR ability of the phone and only displays in normal 2d mode, although they do recognize the controller. For _Need for Speed: No Limits VR_ it goes into VR mode but nothing is displayed - only a black image. The only apps that work are newer ones like VRTV, VR Browser, Sites in VR, etc.

**Comment by DavidModPhone** [comment]
Thank you for liking this Module 😄:, mmmh some apps doesnt run in VR mode?, my Redmi Note 8T with Magisk and this module was actually opening games in VR mode, maybe something has to do with your Daydream App? or your Phone?

**Comment by skygate2012** [comment]
The game can be played in 2d mode with the controller, so I guess the obb issue can be ruled out. I installed all three apks from your zip package. My phone is XT2125-4. I don't know if I can give you a log file or something. Also I noticed that apps with cardboard support would work fine, those that were only developed for DayDream sometimes don't enter VR mode.

**Comment by DavidModPhone** [comment]
> The game can be played in 2d mode with the controller, so I guess the obb issue can be ruled out. I installed all three apks from your zip package. My phone is XT2125-4. I don't know if I can give you a log file or something. Also I noticed that apps with cardboard support would work fine, those that were only developed for DayDream sometimes don't enter VR mode.

Maybe reinstall the Daydream app?

**Comment by skygate2012** [comment]
I've tried reinstalling, clearing storage, nothing works.
But great news! I finally made everything work fine by also installing the [Pixelify](https://github.com/Kingsman44/Pixelify) module to spoof Pixel device. I guess there are additional properties required that is missing from your module? If you are interested, maybe take a look.

**Comment by DavidModPhone** [comment]
Good that you fixed it, maybe i should take a look on similar plugins like this and maybe make a new version of this module

**Comment by DavidModPhone** [comment]
Well, I guess with the new update this issue would be fixed, also i think taking the lsposed spoof module thing is good, you don't have to edit the build.prop file but you have to install LSPosed to make it work
