### ISSUE TITLE
Wrong resolution 

### ISSUE THREAD

**Issue by EdrickCodes** [DavidModPhone/DaydreamVR_Service#3]
It works on my rooted Infinix hot 40 pro but the only problem is the wrong resolution.

See video;

https://github.com/DavidModPhone/DaydreamVR_Service/assets/112858301/0f5a2b19-6106-4f8a-8a42-4c3ae5123840

**Comment by DavidModPhone** [comment]
The Daydream App on newer Android Versions may do not work properly, however try reinstalling the module and the app

**Comment by EdrickCodes** [comment]
You mean that I uninstall the module and put it back?

**Comment by DavidModPhone** [comment]
> You mean that I uninstall the module and put it back?

Yes, even the app

**Comment by EdrickCodes** [comment]
https://github.com/DavidModPhone/DaydreamVR_Service/assets/112858301/19b5a069-c4fb-4630-9f42-e3a1cd253795

Tried, it's still widescreen

**Comment by EdrickCodes** [comment]
https://github.com/DavidModPhone/DaydreamVR_Service/assets/112858301/80b548b7-670b-454f-beea-a78e58220550

**Comment by DavidModPhone** [comment]
> Screen_Recording_20240530_103135.mp4

maybe it has to do with custom rom? or your phone's stock os?

**Comment by skygate2012** [comment]
Hi @EdrickCodes, seems like you're facing the exact same issue as [mine](https://github.com/DavidModPhone/DaydreamVR_Service/issues/1#issuecomment-2069292863). Try installing the [Pixelify](https://github.com/Kingsman44/Pixelify) module in addition.

**Comment by skygate2012** [comment]
Try installing the [Pixelify](https://github.com/Kingsman44/Pixelify) module in addition and see if it works.
